language: java
jdk: 
- openjdk13

addons:
    sonarcloud:
        organization: "lorenzot8942"
        token:
            secure: "82c7ce2a9e6a15cbe3b26e5716a72d3d2993ff32"
script: 
- ant build
- sonar-scanner